### ISSUE TITLE
echarts 3.71  react 15.5.4 echarts-for-react 1.4.4  引用echarts-wordcloud1.1.3 报错

### ISSUE THREAD

**Issue by aLIEzsss4** [ecomfe/echarts-wordcloud#68]
H:\dbA0720testCharts\node_modules\_echarts-wordcloud@1.1.3@echarts-wordcloud\src\layout.js:12
if (!window.setImmediate) {
^
ReferenceError: window is not defined
    at Object.<anonymous> (H:\dbA0720testCharts\node_modules\_echarts-wordcloud@1.1.3@echarts-wordcloud\src\layout.js:12:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (H:\dbA0720testCharts\node_modules\_echarts-wordcloud@1.1.3@echarts-wordcloud\src\wordCloud.js:7:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

layout.js没有找到window.

**Comment by samwangdd** [comment]
请问，这个问题解决了吗？

**Comment by mkdreams** [comment]
没人关了？
